import { FoodPreset } from '@/types';

export const foodPresets: FoodPreset[] = [
  { name: 'Apple', calories: 95, protein: 0, carbs: 25, fat: 0, serving_size: '1 medium' },
  { name: 'Banana', calories: 105, protein: 1, carbs: 27, fat: 0, serving_size: '1 medium' },
  { name: 'Chicken Breast', calories: 165, protein: 31, carbs: 0, fat: 4, serving_size: '100g' },
  { name: 'Rice', calories: 206, protein: 4, carbs: 45, fat: 0, serving_size: '1 cup cooked' },
  { name: 'Eggs', calories: 78, protein: 6, carbs: 1, fat: 5, serving_size: '1 large' },
  { name: 'Coffee', calories: 2, protein: 0, carbs: 0, fat: 0, serving_size: '1 cup black' },
  { name: 'Pasta', calories: 220, protein: 8, carbs: 43, fat: 1, serving_size: '1 cup cooked' },
  { name: 'Salmon', calories: 208, protein: 20, carbs: 0, fat: 13, serving_size: '100g' },
  { name: 'Bread', calories: 79, protein: 3, carbs: 14, fat: 1, serving_size: '1 slice' },
  { name: 'Greek Yogurt', calories: 100, protein: 17, carbs: 6, fat: 1, serving_size: '170g' },
  { name: 'Oatmeal', calories: 154, protein: 5, carbs: 27, fat: 3, serving_size: '1 cup cooked' },
  { name: 'Avocado', calories: 240, protein: 3, carbs: 12, fat: 22, serving_size: '1 whole' },
  { name: 'Sweet Potato', calories: 103, protein: 2, carbs: 24, fat: 0, serving_size: '1 medium' },
  { name: 'Broccoli', calories: 55, protein: 4, carbs: 11, fat: 1, serving_size: '1 cup' },
  { name: 'Almonds', calories: 164, protein: 6, carbs: 6, fat: 14, serving_size: '28g' },
  { name: 'Milk', calories: 149, protein: 8, carbs: 12, fat: 8, serving_size: '1 cup whole' },
  { name: 'Cheese', calories: 113, protein: 7, carbs: 0, fat: 9, serving_size: '28g cheddar' },
  { name: 'Steak', calories: 271, protein: 26, carbs: 0, fat: 18, serving_size: '100g' },
  { name: 'Orange', calories: 62, protein: 1, carbs: 15, fat: 0, serving_size: '1 medium' },
  { name: 'Peanut Butter', calories: 188, protein: 7, carbs: 7, fat: 16, serving_size: '2 tbsp' },
  { name: 'Protein Shake', calories: 120, protein: 24, carbs: 3, fat: 1, serving_size: '1 scoop' },
  { name: 'Salad', calories: 20, protein: 1, carbs: 4, fat: 0, serving_size: '1 cup mixed greens' },
];
